// 사용법: PW_MODULE=<playwright 경로> CHROME=<chromium 실행파일> node tests/smoke.js
const { chromium } = require(process.env.PW_MODULE || 'playwright');
const http = require('http'), fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const srv = http.createServer((q, r) => { const f = path.join(root, q.url === '/' ? 'index.html' : q.url.split('?')[0]);
  fs.readFile(f, (e, d) => { if (e) { r.statusCode = 404; return r.end(); } r.setHeader('content-type', f.endsWith('.js') ? 'text/javascript' : f.endsWith('.css') ? 'text/css' : 'text/html'); r.end(d); }); });
(async () => {
  await new Promise(r => srv.listen(0, r));
  const url = 'http://localhost:' + srv.address().port + '/';
  const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] });
  const pg = await (await b.newContext({ viewport: { width: 390, height: 800 } })).newPage();
  const errs = []; pg.on('pageerror', e => errs.push(e.message));
  let dialogs = 0; pg.on('dialog', d => { dialogs++; d.accept(); });
  await pg.route(/unpkg\.com|openstreetmap/, r => r.abort());
  let n = 0; const ok = (c, m) => { if (!c) { console.error('FAIL', m); process.exitCode = 1; } else { n++; console.log('ok -', m); } };
  await pg.goto(url);
  ok(await pg.locator('h1').innerText() === '전주 가족 1박 2일', '기본 여행 로드');
  ok(await pg.locator('.stepper button').count() === 9, '1일차 9곳 스텝퍼');
  await pg.click('[data-act=status][data-v=arrived]'); await pg.click('.big-btn');
  ok(await pg.locator('.stepper button.done').count() === 1, '첫 장소 완료 처리 후 다음 장소');
  await pg.fill('textarea[data-act=memo]', '<img src=x onerror=alert(1)>메모'); await pg.waitForTimeout(600);
  await pg.click('[data-act=tab][data-id=plan]');
  await pg.click('[data-act=day][data-id="2"]');
  ok(await pg.locator('.badge.must').count() === 1, '2일차 필수(전주향교) 표시');
  await pg.click('[data-act=toggle] >> nth=1');
  await pg.reload(); await pg.click('[data-act=tab][data-id=plan]'); await pg.click('[data-act=day][data-id="2"]');
  ok(await pg.locator('.tl-item.off').count() >= 1, '제외 상태 새로고침 후 유지');
  await pg.click('[data-act=plan][data-id=experience]');
  ok(await pg.locator('.badge.must').count() >= 1, '대안 전환 후 필수 유지');
  await pg.click('[data-act=tab][data-id=places]'); await pg.click('[data-act=place-form]');
  await pg.fill('dialog [name=name]', '<b>내 카페</b>'); await pg.fill('dialog [name=lat]', '95'); await pg.fill('dialog [name=lon]', '127');
  await pg.click('dialog button[value=ok]'); await pg.waitForTimeout(200);
  ok(await pg.locator('dialog').count() === 1, '잘못된 좌표는 저장 거부');
  await pg.fill('dialog [name=lat]', '35.81'); await pg.click('dialog button[value=ok]'); await pg.waitForTimeout(300);
  ok(await pg.locator('.card h3', { hasText: '<b>내 카페</b>' }).count() === 1, '사용자 장소 저장·HTML 이스케이프');
  ok(await pg.locator('.card h3 b').count() === 0, 'HTML 태그가 실행되지 않음');
  await pg.click('[data-act=tab][data-id=map]');
  ok(await pg.locator('#map').count() === 1, '지도 영역(라이브러리 차단 시에도 렌더)');
  ok(await pg.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '모바일 가로 스크롤 없음');
  ok(dialogs === 0, '메모 XSS 미실행');
  ok(errs.length === 0, '페이지 오류 없음 ' + errs.join('|'));
  console.log(n + ' browser checks passed'); await b.close(); srv.close();
})();
